# Site
repository: goodslee92/goodslee92.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이 재화
title: Senior BackEnd Developer
email: leejh3810@gmail.com
website: https://github.com/goodslee92

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: goodslee92
instagram_username: jh._.zzzz

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 이 재화입니다. 저는 웹 어플리케이션 백엔드 개발자입니다. 
  시스템 개발 및 운영 경험과 안드로이드 앱 개발 경험이 있습니다. 뿐만 아니라 프로젝트 관리 경험도 있습니다.
  
  저는 여러 회사에서 팀워크와 리더십 스킬을 쌓았습니다. 
  특히 일본 도쿄에서 약 7년간 금융, 통신업, 건설, 보험, 연금 등의 각종 분야에서 새로운 스킬에 도전하며 글로벌 기업에서 경험을 쌓아왔습니다.
  
  저의 주요 기술 스택은 <mark>Java</mark> 와 <mark>Kotlin</mark> 그리고 <mark>새로운 기술에 대한 도전 정신</mark> 입니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BGF Global Back Office System
        sub_title: Project Leader, Senior BackEnd Developer
        caption: August 2023 - Present
        quote: >
          BGF글로벌 백 오피스 시스템 운영 및 관리
        description: | # this will include new lines to allow paragraphs
          BGF글로벌 카자흐스탄, 몽골, 베트남 등 백오피스 시스템의 설계, 개발, 테스트, 오픈, 운영 및 멤버 관리를 담당하였습니다. <br>
          기술스택
          - Java, JSP/Servlet, AxBoot, MSSQL, Git, SVN

      - title: Sony Android Smart Tv App Develop
        sub_title:  Sub Leader, System Engineer
        caption: July 2020 - May 2023
        quote: >
          Android Tv App 개발
        description: | # this will include new lines to allow paragraphs
          Sony Android Smart Tv에 내장되는 Tv 관련 앱 개발 프로젝트입니다.
          Channel Scan, Tv Settings, 녹화 등의 기능을 담당하였습니다.
          MVC 디자인 패턴의 기존 Java 코드를 MVVM 디자인 패턴의 Kotlin 코드로 신규 개발하였습니다.
          기술스택
          - Java, Kotlin, ORACLE, Github, SourceTree, Jenkins, AWS, JIRA

      - title: Sony Android Smart Tv App Develop
        sub_title:  Sub Leader, System Engineer
        caption: July 2020 - May 2023
        quote: >
          Android Tv App 개발
        description: | # this will include new lines to allow paragraphs
          Sony Android Smart Tv에 내장되는 Tv 관련 앱 개발 프로젝트입니다.
          Channel Scan, Tv Settings, 녹화 등의 기능을 담당하였습니다.
          MVC 디자인 패턴의 기존 Java 코드를 MVVM 디자인 패턴의 Kotlin 코드로 신규 개발하였습니다.
          기술스택
          - Java, Kotlin, ORACLE, Github, SourceTree, Jenkins, AWS, JIRA

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한국후지쯔(주)
        sub_title: Project Leader, Web Application BackEnd Developer
        caption: August 2023 ~ Present
        quote: >
          quote..
        description: | # this will include new lines to allow paragraphs
          description..

      - title: (주)브릿지
        sub_title: Android App Developer, Web Application BackEnd Developer
        caption: December 2018 ~ March 2023
        quote: >
          웹 어플리케이션 개발 및 운영.
          안드로이드 앱 개발 및 운영.
        description: | # this will include new lines to allow paragraphs
          하기 프로젝트 참여.

      - title: (주)Nuvo Cyber Business
        sub_title:  System Engineer
        caption: July 2016 ~ November 2018
        quote: >
          웹 어플리케이션 개발 및 운영.
        description: | # this will include new lines to allow paragraphs
          하기 프로젝트 참여.

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 기술 스택
        description: >
          - Java, Kotlin, JavaScript, Jsp, Jquery, HTML/CSS, SWING, Python, Ruby, ORACLE, MySQL, MSSQL, HIRDB
          - Xml, Json, Junit, DJunit, IBatis, MyBatis, Struts2, JPA, Spring, Dia(Spring) etc

      - title: 기타 툴
        description: >
          - Eclipse, Android Studio, IntelliJ, VisualStudio Code, WSSD, RAD, Appium, Linux, Windows
          - AWS, Jenkins, Git, Github, SVN, Jira, Confluence, SourceTree, Dooray, Flow, Redmine, ServiceNow, SalesForce
          - Microsoft Teams, Slack etc

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 영남이공대학교
        sub_title: 컴퓨터계열 시스템프로그래밍 전공
        caption: 2011 ~ 2016 <br> 졸업

      - layout: top-middle
        title: 대구도원고등학교
        sub_title: 인문계열
        caption: 2008 ~ 2011 <br> 졸업

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      시스템 개발 및 안드로이드 앱 개발에 대한 저의 관심과 함께 저의 다른 관심과 취미는 다음과 같습니다.
      - 게임
      - 영화 감상
      - 드라이브
      - 당구
      - 클레이 사격 등

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
