# Site
repository: goodslee92/goodslee92.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이 재화
title: Senior BackEnd Developer
email: leejh3810@gmail.com
website: https://github.com/goodslee92

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: goodslee92
instagram_username: jh._.zzzz

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 이 재화입니다. 
  <mark>생년월일</mark>: 1992.11.20
  <mark>연락처</mark>: 010-3021-4520
  <mark>주소</mark>: 서울시 동작구 상도로54길 54
  <mark>경력</mark>: 7년 2개월
  
  시스템 개발 및 운영, 안드로이드 앱 개발, 프로젝트 관리 경험이 있는 백엔드 개발자입니다.
  
  저는 여러 회사에서 팀워크와 리더십 스킬을 쌓았습니다. 
  특히 일본 도쿄에서 약 7년간 금융, 보험, 연금, 전력, 통신, 유통 등의 각종 분야에서 새로운 스킬에 도전하며 글로벌한 경험을 쌓아왔습니다.
  
  저의 주요 기술 스택은 <mark>Java</mark> 와 <mark>Kotlin</mark> 그리고 <mark>새로운 기술에 대해 끊임없이 탐구하고 도전하는 정신</mark> 입니다.

content:
  - title: Projects(Korea) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BGF Global Back Office System
        sub_title: Project Leader, Senior BackEnd Developer
        caption: August 2023 - Present
        quote: >
          BGF글로벌 백 오피스 시스템 운영 및 관리
        description: | # this will include new lines to allow paragraphs
          BGF글로벌 카자흐스탄, 몽골, 베트남 등 백오피스 시스템의 설계, 개발, 테스트, 오픈, 운영 및 멤버 관리를 담당하였습니다. <br>
          <mark>기술스택</mark><br>
          - Java, JSP/Servlet, AxBoot, MSSQL
          - Eclipse, IntelliJ
          - Git, SVN, Dooray, Slack, Microsoft Teams

  - title: Projects(Japan)
    layout: list
    content:
      - layout : left
        title: Sony Android Smart Tv App 개발
        sub_title:  Sub Leader, System Engineer
        caption: July 2020 - May 2023
        quote: >
          Android Smart Tv App 개발
        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark>: 도쿄 오오사키   <mark>업종</mark>: 통신업<br>
          <mark>업무 내용</mark>: Sony Android Smart Tv에 내장되는 Tv 관련 앱 개발 프로젝트입니다.<br>
          MVC 디자인 패턴의 기존 Java 코드를 MVVM 디자인 패턴의 Kotlin 코드로 신규 개발하였습니다.<br>
          지상파 및 케이블 Channel Scan 기능, Tv에 대한 전반적인 설정 기능, 시간 지정 또는 채널 지정 녹화 기능의 기능 개선 및 유지보수를 담당하였습니다.<br>
          <mark>기술 스택</mark><br>
          - Java, Kotlin, Dagger, Hilt, DataBinding, Coroutine, Python, Ruby, ORACLE
          - Android Studio, Visual Studio Code, Appium
          - Github, Jenkins, AWS, JIRA, Counfluence, SourceTree, Astah, Microsoft Teams

      - title: 주택, 빌딩 유통 견적 시스템 개발 및 운영
        sub_title: System Engineer
        caption: September 2019 ~ June 2020
        quote: >
          주택, 빌딩 유통 견적 시스템 고도화 및 운영 유지보수
        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark>: 도쿄 몬젠나카쵸   <mark>업종</mark>: 유통업<br>
          <mark>업무 내용</mark>: 건축 시공에 필요한 자재에 대해 재고 관리 및 발주 그리고 가견적 기능을 제공하는 시스템의 고도화 프로젝트입니다.<br> 
          신규 기능 추가 및 고객 문의 대응 및 유지보수를 담당하였습니다.
          <mark>기술 스택</mark><br>
          - Java, Jsp, JavaScript, Swing, Struts2, Oracle
          - Eclipse, WSSD
          - SVN, Jenkins, ServiceNow, SalesForce

      - title:
        sub_title: System Engineer
        caption:
        quote: >

        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark>: 도쿄 <br>
          <mark>업무 내용</mark>: .<br> 
          <mark>기술 스택</mark><br>
          - 

      - title:
        sub_title: System Engineer
        caption:
        quote: >

        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark>: 도쿄 <br>
          <mark>업무 내용</mark>: .<br> 
          <mark>기술 스택</mark><br>
          - 

      - title:
        sub_title: System Engineer
        caption:
        quote: >

        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark>: 도쿄 <br>
          <mark>업무 내용</mark>: .<br> 
          <mark>기술 스택</mark><br>
          - 

  - title: Experience(Korea) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한국후지쯔(주)
        sub_title: Project Leader, BackEnd Developer
        caption: August 2023 ~ Present
        quote: >
          시스템 개발 및 운영.
          프로젝트 관리 및 멤버 관리.
        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark> : 서울 종로구 <br>
          <mark>경험</mark> : TODO

  - title: Experience(Japan) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)브릿지
        sub_title: Android App Developer, BackEnd Developer
        caption: December 2018 ~ March 2023
        quote: >
          시스템 개발 및 운영.
          안드로이드 앱 개발 및 운영유지보수.
        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark> : 일본 도쿄 <br>
          <mark>경험</mark> : 글로벌 대기업의 업무 프로세스 및 협업 능력을 배웠으며, 서브리더로써의 멤버 관리 경험을 익혔습니다.<br>
          또한, Java 이외의 새로운 역량을 발전시키고자 안드로이드 앱 개발에 도전하여 Kotlin 및 Coroutine 과 같은 기술 역량을 배울 수 있었습니다.

      - title: (주)Nuvo Cyber Business
        sub_title: BackEnd Developer
        caption: July 2016 ~ November 2018
        quote: >
          시스템 개발 및 운영유지보수.
        description: | # this will include new lines to allow paragraphs
          <mark>소재지</mark> : 일본 도쿄 <br>
          <mark>경험</mark> : 일본 기업에 신입 사원으로 입사 후, 현업에서 개발 능력과 외국어 능력을 병행하여 공부하였습니다. <br>
          3년차가 되던 해에 4명의 멤버로 구성된 팀을 이끌어 프로젝트를 성황리에 마감할 수 있도록 리드하였습니다.

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 기술 스택
        description: |
          - <mark>언어</mark> : Java, Kotlin, Python 
          - <mark>RDBMS</mark> : ORACLE, MySQL, MSSQL, HIRDB, DB2, SSMS

      - title: 기타
        description: |
          - <mark>IDEA</mark> : IntelliJ, Eclipse, Android Studio, VisualStudio Code, WSSD, RAD
          - <mark>형상관리</mark> : AWS, Jenkins, Git, Github, SVN
          - <mark>협업툴</mark> : Jira, Confluence, SourceTree, Teams, Slack, Dooray, Flow, Redmine, ServiceNow, SalesForce
          - <mark>기타</mark> : JavaScript, Jsp, Jquery, HTML/CSS, Spring, Dia, Struts2, JPA, IBatis, MyBatis, Xml, Json, Junit, DJunit, PowerMock

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 영남이공대학교
        sub_title: 컴퓨터계열 시스템프로그래밍 전공
        caption: 2011 ~ 2016 <br> 졸업

      - layout: top-middle
        title: 대구도원고등학교
        sub_title: 인문계열
        caption: 2008 ~ 2011 <br> 졸업

  - title: A Little More About Me
    layout: list
    content:
      - layout: top-middle
        sub_title: |
          병역 : 육군 <br>
          복무 기간 : 2012.05 ~ 2014.02 <br>
          계급 : 병장 만기 제대 <br><br>
          
          시스템 개발 및 안드로이드 앱 개발에 대한 저의 관심과 함께 저의 다른 관심과 취미는 다음과 같습니다. <br>
          - 게임 <br>
          - 영화 감상 <br>
          - 드라이브 <br>
          - 당구 <br>
          - 클레이 사격

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
